'use client'

import { IntegrationDef } from './types'

export const allIntegrations: IntegrationDef[] = [

  /* ===== FELLES (alle bransjer) ===== */
  {
    service: 'vipps',
    name: 'Vipps MobilePay',
    description: 'Automatisk fakturering og betalingspåminnelser via Vipps.',
    icon: '💳',
    color: '#ff5b24',
    category: 'Felles',
    fields: [
      { key: 'client_id', label: 'Client ID', placeholder: 'Lim inn din Vipps Client ID', type: 'text' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Lim inn din Vipps Client Secret', type: 'password' },
      { key: 'merchant_serial', label: 'Merchant Serial Number (MSN)', placeholder: 'F.eks. 123456', type: 'text', helpText: 'Finner du i Vipps-portalen under Utvikler → API-nøkler' },
      { key: 'subscription_key', label: 'Ocp-Apim-Subscription-Key', placeholder: 'Lim inn subscription key', type: 'password' },
    ],
    helpUrl: 'https://developer.vippsmobilepay.com/docs/getting-started/',
    helpLabel: 'Hvordan finner jeg API-nøklene?',
    usedFor: ['Automatisk fakturering', 'Betalingspåminnelser', 'Refusjon-håndtering'],
  },
  {
    service: 'tripletex',
    name: 'Tripletex',
    description: 'Synkroniser faktura, kunder og regnskap automatisk.',
    icon: '📊',
    color: '#2563eb',
    category: 'Felles',
    fields: [
      { key: 'consumer_token', label: 'Consumer Token', placeholder: 'Lim inn din consumer token', type: 'password', helpText: 'Opprett en integrasjon i Tripletex under Innstillinger → API-tilgang' },
      { key: 'employee_token', label: 'Employee Token', placeholder: 'Lim inn din employee token', type: 'password' },
    ],
    helpUrl: 'https://tripletex.no/v2-docs/',
    helpLabel: 'Hvordan oppretter jeg API-tilgang?',
    usedFor: ['Auto-fakturering', 'Kundesynkronisering', 'Regnskapseksport'],
  },
  {
    service: 'fiken',
    name: 'Fiken',
    description: 'Regnskap og fakturering for små bedrifter.',
    icon: '🧾',
    color: '#00b4d8',
    category: 'Felles',
    fields: [
      { key: 'api_token', label: 'API-token', placeholder: 'Lim inn din Fiken API-token', type: 'password', helpText: 'Generer token i Fiken under Innstillinger → API' },
      { key: 'company_slug', label: 'Firma-slug', placeholder: 'F.eks. mitt-firma-as', type: 'text', helpText: 'Finner du i URL-en når du er logget inn i Fiken' },
    ],
    helpUrl: 'https://api.fiken.no/api/v2/docs/',
    helpLabel: 'Hvordan finner jeg API-token?',
    usedFor: ['Auto-fakturering', 'Regnskapsføring', 'Kundesynkronisering'],
  },
  {
    service: 'google_calendar',
    name: 'Google Calendar',
    description: 'Automatisk booking og møtepåminnelser koblet til kalenderen din.',
    icon: '📅',
    color: '#16a34a',
    category: 'Felles',
    fields: [
      { key: 'calendar_id', label: 'Kalender-ID', placeholder: 'din@gmail.com eller kalender-ID', type: 'text', helpText: 'Finner du i Google Calendar → Innstillinger → Kalender-ID' },
    ],
    helpUrl: 'https://support.google.com/calendar/answer/37083',
    helpLabel: 'Hvordan finner jeg min kalender-ID?',
    usedFor: ['Auto-booking', 'Møtepåminnelser', 'Kalender-synkronisering'],
  },
  {
    service: 'outlook',
    name: 'Microsoft Outlook',
    description: 'Synkroniser kalender, e-post og kontakter via Microsoft 365.',
    icon: '📧',
    color: '#0078d4',
    category: 'Felles',
    fields: [
      { key: 'client_id', label: 'Application (Client) ID', placeholder: 'Lim inn Azure AD Client ID', type: 'text', helpText: 'Opprett en app i Azure Portal → App Registrations' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Lim inn client secret', type: 'password' },
      { key: 'tenant_id', label: 'Tenant ID', placeholder: 'Lim inn din Azure Tenant ID', type: 'text' },
    ],
    helpUrl: 'https://learn.microsoft.com/en-us/graph/auth-register-app-v2',
    helpLabel: 'Hvordan setter jeg opp Microsoft-integrasjon?',
    usedFor: ['Kalender-synkronisering', 'E-post-automatisering', 'Kontaktsynkronisering'],
  },
  {
    service: 'twilio',
    name: 'Twilio',
    description: 'SMS-varsler og telefonintegrasjon for kundeoppfølging.',
    icon: '📱',
    color: '#e11d48',
    category: 'Felles',
    fields: [
      { key: 'account_sid', label: 'Account SID', placeholder: 'Lim inn din Twilio Account SID', type: 'text' },
      { key: 'auth_token', label: 'Auth Token', placeholder: 'Lim inn din auth token', type: 'password' },
      { key: 'phone_number', label: 'Twilio-telefonnummer', placeholder: '+47XXXXXXXX', type: 'text', helpText: 'Telefonnummeret du har kjøpt i Twilio' },
    ],
    helpUrl: 'https://www.twilio.com/docs/usage/api',
    helpLabel: 'Hvor finner jeg Account SID og Auth Token?',
    usedFor: ['SMS-påminnelser', 'Kundevarsler', 'Telefon-integrasjon'],
  },
  {
    service: 'sendgrid',
    name: 'SendGrid',
    description: 'Automatiske e-poster, bekreftelser og nyhetsbrev.',
    icon: '✉️',
    color: '#1a82e2',
    category: 'Felles',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din SendGrid API key', type: 'password', helpText: 'Opprett en API key i SendGrid under Settings → API Keys' },
    ],
    helpUrl: 'https://docs.sendgrid.com/for-developers/sending-email/api-getting-started',
    helpLabel: 'Hvordan oppretter jeg en API-nøkkel?',
    usedFor: ['Auto-epost', 'Bookingbekreftelser', 'Nyhetsbrev'],
  },
  {
    service: 'slack',
    name: 'Slack',
    description: 'Direkte varsler og statusoppdateringer til Slack-kanaler.',
    icon: '💬',
    color: '#611f69',
    category: 'Kommunikasjon & Prosjekt',
    fields: [
      { key: 'webhook_url', label: 'Webhook URL', placeholder: 'https://hooks.slack.com/services/...', type: 'password', helpText: 'Opprett en Incoming Webhook i Slack Workspace App Directory' },
      { key: 'channel', label: 'Kanal', placeholder: '#notifications', type: 'text' },
    ],
    helpUrl: 'https://api.slack.com/messaging/webhooks',
    helpLabel: 'Hvordan setter jeg opp Slack webhooks?',
    usedFor: ['Varsler', 'Statusoppdateringer', 'Team-notifikasjoner'],
  },
  {
    service: 'microsoft_teams',
    name: 'Microsoft Teams',
    description: 'Integrer varsler direkte til Teams-kanaler og -chatter.',
    icon: '👥',
    color: '#464eb8',
    category: 'Kommunikasjon & Prosjekt',
    fields: [
      { key: 'webhook_url', label: 'Webhook URL', placeholder: 'https://outlook.webhook.office.com/webhookb2/...', type: 'password', helpText: 'Opprett en Connector i Teams og kopier Webhook URL' },
    ],
    helpUrl: 'https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using',
    helpLabel: 'Hvordan setter jeg opp Teams Connectors?',
    usedFor: ['Varsler', 'Chatt-integrasjon', 'Oppgaver'],
  },
  {
    service: 'asana',
    name: 'Asana',
    description: 'Opprett oppgaver og prosjekter direkte fra automiseringer.',
    icon: '✅',
    color: '#0066cc',
    category: 'Kommunikasjon & Prosjekt',
    fields: [
      { key: 'api_token', label: 'Personal Access Token', placeholder: 'Lim inn din Asana API token', type: 'password', helpText: 'Generer under My Profile Settings → Apps → Developer Apps' },
      { key: 'project_id', label: 'Prosjekt-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://developers.asana.com/docs/authentication',
    helpLabel: 'Hvor finner jeg Asana API-token?',
    usedFor: ['Oppgaver', 'Prosjektstyring', 'Team-koordinering'],
  },
  {
    service: 'monday',
    name: 'Monday.com',
    description: 'Automatiser arbeidsflyten med Monday.com oppgaver og oppdateringer.',
    icon: '📋',
    color: '#0055cc',
    category: 'Kommunikasjon & Prosjekt',
    fields: [
      { key: 'api_token', label: 'API Token', placeholder: 'Lim inn din Monday API token', type: 'password', helpText: 'Hent token under Admin → Developer → Tokens' },
      { key: 'board_id', label: 'Brett-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://developer.monday.com/api-reference/docs',
    helpLabel: 'Hvordan finner jeg Monday API-token?',
    usedFor: ['Oppgaver', 'Arbeidsflytstyrte', 'Rapportering'],
  },
  {
    service: 'notion',
    name: 'Notion',
    description: 'Lagre data direkte til Notion-databaser.',
    icon: '📄',
    color: '#000000',
    category: 'Kommunikasjon & Prosjekt',
    fields: [
      { key: 'api_token', label: 'Notion Internal Token', placeholder: 'secret_...', type: 'password', helpText: 'Lag en integrasjon i Notion Settings → Integrations' },
      { key: 'database_id', label: 'Database-ID', placeholder: 'abc123def456...', type: 'text', helpText: 'Finner du i URL-en når du åpner databasen' },
    ],
    helpUrl: 'https://developers.notion.com/docs/getting-started/introduction',
    helpLabel: 'Hvordan setter jeg opp Notion API?',
    usedFor: ['Datalagrering', 'Dokumentasjon', 'Databasesynkronisering'],
  },
  {
    service: 'facebook',
    name: 'Facebook / Meta',
    description: 'Publiser innhold og administrer Facebook-sider automatisk.',
    icon: 'f',
    color: '#1877f2',
    category: 'Sosiale Medier',
    fields: [
      { key: 'access_token', label: 'Page Access Token', placeholder: 'Lim inn din Meta access token', type: 'password', helpText: 'Hent fra Meta Business Suite eller Graph API' },
      { key: 'page_id', label: 'Side-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://developers.facebook.com/docs/facebook-login/access-tokens',
    helpLabel: 'Hvordan finner jeg Meta access tokens?',
    usedFor: ['Publisering', 'Administrasjon', 'Innholdsplanlegging'],
  },
  {
    service: 'instagram',
    name: 'Instagram (Meta)',
    description: 'Automatiser Instagram-poster og stories via Meta API.',
    icon: '📷',
    color: '#e1306c',
    category: 'Sosiale Medier',
    fields: [
      { key: 'access_token', label: 'Access Token', placeholder: 'Lim inn din Meta access token', type: 'password' },
      { key: 'business_account_id', label: 'Business Account ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://developers.facebook.com/docs/instagram-api',
    helpLabel: 'Hvordan setter jeg opp Instagram API?',
    usedFor: ['Publisering', 'Stories', 'Kampanjer'],
  },
  {
    service: 'twitter',
    name: 'X (Twitter)',
    description: 'Post tweets automatisk fra automiseringer.',
    icon: '𝕏',
    color: '#000000',
    category: 'Sosiale Medier',
    fields: [
      { key: 'bearer_token', label: 'Bearer Token', placeholder: 'Lim inn ditt Twitter bearer token', type: 'password', helpText: 'Generer i Twitter Developer Portal under Keys & Tokens' },
    ],
    helpUrl: 'https://developer.twitter.com/en/docs/twitter-api',
    helpLabel: 'Hvordan oppretter jeg Twitter API-tokens?',
    usedFor: ['Publisering', 'Tweets', 'X-integrasjon'],
  },
  {
    service: 'tiktok',
    name: 'TikTok',
    description: 'Publiser videoer og administrer TikTok-kontoer automatisk.',
    icon: '🎵',
    color: '#25f4ee',
    category: 'Sosiale Medier',
    fields: [
      { key: 'access_token', label: 'Access Token', placeholder: 'Lim inn ditt TikTok access token', type: 'password' },
      { key: 'account_id', label: 'Account ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://developers.tiktok.com/doc/',
    helpLabel: 'Hvordan setter jeg opp TikTok API?',
    usedFor: ['Publisering', 'Videoer', 'Kampanjer'],
  },
  {
    service: 'linkedin',
    name: 'LinkedIn',
    description: 'Del innhold og administrer LinkedIn-profiler og sider.',
    icon: '💼',
    color: '#0a66c2',
    category: 'Sosiale Medier',
    fields: [
      { key: 'access_token', label: 'Access Token', placeholder: 'Lim inn ditt LinkedIn access token', type: 'password', helpText: 'Opprett en app i LinkedIn Developer Portal' },
      { key: 'organization_id', label: 'Organisasjons-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://docs.microsoft.com/en-us/linkedin/shared/authentication/authentication',
    helpLabel: 'Hvordan setter jeg opp LinkedIn API?',
    usedFor: ['Innholdsdeling', 'Profiladministrasjon', 'B2B-marketing'],
  },
  {
    service: 'youtube',
    name: 'YouTube',
    description: 'Publiser og administrer YouTube-videoer og kanaler automatisk.',
    icon: '🎥',
    color: '#ff0000',
    category: 'Sosiale Medier',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din YouTube API key', type: 'password', helpText: 'Generer i Google Cloud Console' },
      { key: 'channel_id', label: 'Kanal-ID', placeholder: 'UCxxxxxxxxxxxxxx', type: 'text' },
    ],
    helpUrl: 'https://developers.google.com/youtube/v3/quickstart',
    helpLabel: 'Hvordan oppretter jeg YouTube API-nøkkel?',
    usedFor: ['Publisering', 'Videoer', 'Kanal-administrasjon'],
  },
  {
    service: 'spotify',
    name: 'Spotify',
    description: 'Integrer Spotify-lister og podcaster i automiseringer.',
    icon: '🎵',
    color: '#1db954',
    category: 'Sosiale Medier',
    fields: [
      { key: 'client_id', label: 'Client ID', placeholder: 'Lim inn din Spotify Client ID', type: 'text', helpText: 'Registrer appen i Spotify Developer Portal' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Lim inn din Client Secret', type: 'password' },
    ],
    helpUrl: 'https://developer.spotify.com/documentation/web-api',
    helpLabel: 'Hvordan setter jeg opp Spotify API?',
    usedFor: ['Musikk-integrasjon', 'Podcaster', 'Avspilling'],
  },
  {
    service: 'stripe',
    name: 'Stripe',
    description: 'Håndter betalinger, abonnementer og refusjoner.',
    icon: '💰',
    color: '#5469d4',
    category: 'Betaling & Finans',
    fields: [
      { key: 'api_key', label: 'Secret API Key', placeholder: 'sk_live_...', type: 'password', helpText: 'Hent fra Stripe Dashboard → Developers → API Keys' },
    ],
    helpUrl: 'https://stripe.com/docs/keys',
    helpLabel: 'Hvor finner jeg Stripe API-nøkler?',
    usedFor: ['Betalingsbehandling', 'Abonnementshåndtering', 'Refusjoner'],
  },
  {
    service: 'paypal',
    name: 'PayPal',
    description: 'Integrer PayPal for betalinger og transaksjonsdata.',
    icon: '🅿️',
    color: '#003087',
    category: 'Betaling & Finans',
    fields: [
      { key: 'client_id', label: 'Client ID', placeholder: 'Lim inn din PayPal Client ID', type: 'text' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Lim inn din Client Secret', type: 'password' },
    ],
    helpUrl: 'https://developer.paypal.com/docs/api/overview/',
    helpLabel: 'Hvordan setter jeg opp PayPal API?',
    usedFor: ['Betalinger', 'Transaksjoner', 'Refusjoner'],
  },
  {
    service: 'square',
    name: 'Square',
    description: 'POS-integrasjon, betalinger og kundedata fra Square.',
    icon: '▢',
    color: '#003da5',
    category: 'Betaling & Finans',
    fields: [
      { key: 'access_token', label: 'Access Token', placeholder: 'sq_...', type: 'password', helpText: 'Hent fra Square Developer Dashboard' },
      { key: 'location_id', label: 'Lokasjon-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://developer.squareup.com/docs',
    helpLabel: 'Hvordan finner jeg Square API-tokens?',
    usedFor: ['POS-integrasjon', 'Betalinger', 'Kundedata'],
  },
  {
    service: 'netaxept',
    name: 'Nets Netaxept',
    description: 'Norsk betalingsgateway med fakturering og abonnementer.',
    icon: '🏦',
    color: '#003da5',
    category: 'Betaling & Finans',
    fields: [
      { key: 'merchant_id', label: 'Merchant ID', placeholder: 'Lim inn din Nets Merchant ID', type: 'text' },
      { key: 'api_token', label: 'API Token', placeholder: 'Lim inn ditt API token', type: 'password' },
    ],
    helpUrl: 'https://www.nets.no/bedrift/webhop',
    helpLabel: 'Hvordan setter jeg opp Nets Netaxept?',
    usedFor: ['Norsk betaling', 'Fakturering', 'Abonnement'],
  },
  {
    service: 'resurs_bank',
    name: 'Resurs Bank',
    description: 'Integrert finanse- og kreditløsning for norske bedrifter.',
    icon: '🏦',
    color: '#d62b2f',
    category: 'Betaling & Finans',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Resurs API key', type: 'password' },
      { key: 'store_id', label: 'Butikk-ID', placeholder: 'Lim inn din Store ID', type: 'text' },
    ],
    helpUrl: 'https://partner.resursbank.no/',
    helpLabel: 'Hvordan setter jeg opp Resurs Bank API?',
    usedFor: ['Finansiering', 'Kreditt', 'Betaling'],
  },
  {
    service: 'mailchimp',
    name: 'Mailchimp',
    description: 'E-postmarketing, nyhetsbrev og automatisert kundesegmentering.',
    icon: '📧',
    color: '#ffe01b',
    category: 'Markedsføring & E-post',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Mailchimp API key', type: 'password', helpText: 'Hent fra Account → Extras → API Keys' },
    ],
    helpUrl: 'https://mailchimp.com/developer/marketing/guides/hello-world/',
    helpLabel: 'Hvor finner jeg Mailchimp API-nøkler?',
    usedFor: ['E-postmarketing', 'Nyhetsbrev', 'Automatisering'],
  },
  {
    service: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, e-postmarketing og salgsprosess-automatisering.',
    icon: '🟠',
    color: '#ff7a59',
    category: 'Markedsføring & E-post',
    fields: [
      { key: 'api_key', label: 'Private App Token', placeholder: 'pat-...', type: 'password', helpText: 'Opprett en Private App i HubSpot Settings' },
    ],
    helpUrl: 'https://developers.hubspot.com/docs/api/private-apps',
    helpLabel: 'Hvordan oppretter jeg HubSpot API-tokens?',
    usedFor: ['CRM', 'E-postmarketing', 'Salgsprosesser'],
  },
  {
    service: 'klaviyo',
    name: 'Klaviyo',
    description: 'SMS og e-postmarketing for e-handel og abonnement.',
    icon: '📬',
    color: '#17595f',
    category: 'Markedsføring & E-post',
    fields: [
      { key: 'api_key', label: 'Private API Key', placeholder: 'Lim inn din Klaviyo API key', type: 'password', helpText: 'Hent fra Account → Settings → API Keys' },
    ],
    helpUrl: 'https://developers.klaviyo.com/en/docs/home',
    helpLabel: 'Hvor finner jeg Klaviyo API-nøkler?',
    usedFor: ['SMS-marketer', 'E-postmarketing', 'E-handel'],
  },
  {
    service: 'google_business',
    name: 'Google Business Profile',
    description: 'Administrer anmeldelser og lokale bedriftsprofiler.',
    icon: '🗺️',
    color: '#4285f4',
    category: 'Data & Kart',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Google API key', type: 'password' },
      { key: 'business_id', label: 'Bedrift-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://support.google.com/business/answer/3038063',
    helpLabel: 'Hvordan setter jeg opp Google Business API?',
    usedFor: ['Anmeldelser', 'Bedriftsprofil', 'Lokale oppføringer'],
  },
  {
    service: 'google_maps',
    name: 'Google Maps',
    description: 'Ruteplanning, stedskoder og geolokalisering.',
    icon: '🗺️',
    color: '#4285f4',
    category: 'Data & Kart',
    fields: [
      { key: 'api_key', label: 'Maps API Key', placeholder: 'Lim inn din Google Maps API key', type: 'password', helpText: 'Opprett fra Google Cloud Console' },
    ],
    helpUrl: 'https://developers.google.com/maps/documentation',
    helpLabel: 'Hvordan oppretter jeg Google Maps API-nøkkel?',
    usedFor: ['Ruteplanning', 'Geolokalisering', 'Stedskoder'],
  },
  {
    service: 'finn_generell',
    name: 'Finn.no (generelt)',
    description: 'Data fra Finn.no klassifiserte annonser og markedsplass.',
    icon: '🔍',
    color: '#ff6600',
    category: 'Data & Kart',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Finn API key', type: 'password' },
    ],
    helpUrl: 'https://www.finn.no/about/api',
    helpLabel: 'Hvordan får jeg Finn.no API-tilgang?',
    usedFor: ['Lead-datascraping', 'Markedsdata', 'Konkurrense-analyse'],
  },
  {
    service: 'finn_eiendom',
    name: 'Finn.no (Eiendom)',
    description: 'Eiendomsannonser og eiendomsdata fra Finn.no.',
    icon: '🏠',
    color: '#ff6600',
    category: 'Data & Kart',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Finn Eiendom API key', type: 'password' },
    ],
    helpUrl: 'https://www.finn.no/about/api',
    helpLabel: 'Hvordan får jeg Finn Eiendom API-tilgang?',
    usedFor: ['Eiendomsannonser', 'Markedsanalyse', 'Prisdata'],
  },
  {
    service: 'finn_bil',
    name: 'Finn.no (Bil)',
    description: 'Bilannonser og kjøretøydata fra Finn.no.',
    icon: '🚗',
    color: '#ff6600',
    category: 'Data & Kart',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Finn Bil API key', type: 'password' },
    ],
    helpUrl: 'https://www.finn.no/about/api',
    helpLabel: 'Hvordan får jeg Finn Bil API-tilgang?',
    usedFor: ['Bilannonser', 'Kjøretøydata', 'Inventar-synkronisering'],
  },
  {
    service: 'bygglet',
    name: 'Bygglet',
    description: 'Integrer tidsregistrering og prosjektstyring for bygg.',
    icon: '🏗️',
    color: '#005eb8',
    category: 'Bygg & Håndverk',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Bygglet API key', type: 'password' },
      { key: 'company_id', label: 'Bedrift-ID', placeholder: 'Lim inn din bedrift-ID', type: 'text' },
    ],
    helpUrl: 'https://www.bygglet.no/api',
    helpLabel: 'Hvordan setter jeg opp Bygglet API?',
    usedFor: ['Tidsregistrering', 'Prosjektstyring', 'Fakturering'],
  },
  {
    service: 'fonn',
    name: 'FONN',
    description: 'Kvalitetssikring og datastyring for byggebransjen.',
    icon: '📋',
    color: '#005eb8',
    category: 'Bygg & Håndverk',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din FONN API key', type: 'password' },
    ],
    helpUrl: 'https://www.fonn.no/api',
    helpLabel: 'Hvordan får jeg FONN API-tilgang?',
    usedFor: ['Kvalitetssikring', 'Datahåndtering', 'Regulering'],
  },
  {
    service: 'vitec_next',
    name: 'Vitec Next (eiendom)',
    description: 'Eiendomsannonser og objektadministrasjon for eiendomsmeklere.',
    icon: '🏠',
    color: '#003da5',
    category: 'Eiendomsmegling',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Vitec Next API key', type: 'password' },
      { key: 'broker_id', label: 'Megler-ID', placeholder: 'Lim inn din megler-ID', type: 'text' },
    ],
    helpUrl: 'https://www.vitec.no/api',
    helpLabel: 'Hvordan setter jeg opp Vitec Next API?',
    usedFor: ['Eiendomsannonser', 'Objekthåndtering', 'Visninger'],
  },
  {
    service: 'signicat',
    name: 'Signicat',
    description: 'E-signering og identitetsbekreftelse for juridiske dokumenter.',
    icon: '✍️',
    color: '#00a4e4',
    category: 'Eiendomsmegling',
    fields: [
      { key: 'client_id', label: 'Client ID', placeholder: 'Lim inn din Signicat Client ID', type: 'text' },
      { key: 'client_secret', label: 'Client Secret', placeholder: 'Lim inn din Client Secret', type: 'password' },
    ],
    helpUrl: 'https://developer.signicat.io/',
    helpLabel: 'Hvordan setter jeg opp Signicat API?',
    usedFor: ['E-signering', 'Identitetsverifisering', 'Dokumenter'],
  },
  {
    service: 'timely',
    name: 'Timely',
    description: 'Bookingsystem og kundeadministrasjon for salong og wellness.',
    icon: '💇',
    color: '#f39200',
    category: 'Salong & Skjønnhet',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Timely API key', type: 'password' },
      { key: 'business_id', label: 'Bedrift-ID', placeholder: '123456789', type: 'text' },
    ],
    helpUrl: 'https://dev.timelyapp.com/',
    helpLabel: 'Hvordan får jeg Timely API-tilgang?',
    usedFor: ['Bookinger', 'Kundedata', 'Timetabell'],
  },
  {
    service: 'fixit',
    name: 'Fixit',
    description: 'Booking og kundeadministrasjon for service og håndverk.',
    icon: '🔧',
    color: '#00a4e4',
    category: 'Salong & Skjønnhet',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Fixit API key', type: 'password' },
    ],
    helpUrl: 'https://fixit.no/api',
    helpLabel: 'Hvordan får jeg Fixit API-tilgang?',
    usedFor: ['Bookinger', 'Timetabell', 'Kundedata'],
  },
  {
    service: 'autodata',
    name: 'Autodata',
    description: 'Tekniske opplysninger og vedlikeholdsplanlegging for bilverksteder.',
    icon: '🚗',
    color: '#003da5',
    category: 'Bilverksted & Bilforhandler',
    fields: [
      { key: 'username', label: 'Brukernavn', placeholder: 'Lim inn ditt Autodata-brukernavn', type: 'text' },
      { key: 'password', label: 'Passord', placeholder: 'Lim inn ditt Autodata-passord', type: 'password' },
    ],
    helpUrl: 'https://www.autodata-group.com/',
    helpLabel: 'Hvordan setter jeg opp Autodata-integrasjon?',
    usedFor: ['Tekniske opplysninger', 'Vedlikehold', 'Reservedeler'],
  },
  {
    service: 'infomedia',
    name: 'Infomedia',
    description: 'Teknisk informasjon og sparedelopplysninger for bilverksteder.',
    icon: '📚',
    color: '#003da5',
    category: 'Bilverksted & Bilforhandler',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Infomedia API key', type: 'password' },
    ],
    helpUrl: 'https://www.infomedia.no/',
    helpLabel: 'Hvordan får jeg Infomedia API-tilgang?',
    usedFor: ['Teknisk info', 'Sparedelopplysninger', 'Vedlikehold'],
  },
  {
    service: 'booking_com',
    name: 'Booking.com',
    description: 'Channel manager for booking og overnatting.',
    icon: '🏨',
    color: '#003580',
    category: 'Reiseliv & Overnatting',
    fields: [
      { key: 'api_key', label: 'Booking.com API Key', placeholder: 'Lim inn din Booking API key', type: 'password' },
      { key: 'property_id', label: 'Property ID', placeholder: '123456', type: 'text' },
    ],
    helpUrl: 'https://partner.booking.com/en/solutions/extranet',
    helpLabel: 'Hvordan får jeg Booking.com API-tilgang?',
    usedFor: ['Channel manager', 'Bookinger', 'Ledighet'],
  },
  {
    service: 'airbnb',
    name: 'Airbnb',
    description: 'Administrer Airbnb-annonser og bookinger automatisk.',
    icon: '🏘️',
    color: '#ff5a5f',
    category: 'Reiseliv & Overnatting',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Airbnb API key', type: 'password' },
      { key: 'listing_id', label: 'Listing ID', placeholder: '123456', type: 'text' },
    ],
    helpUrl: 'https://www.airbnb.com/host/homes',
    helpLabel: 'Hvordan setter jeg opp Airbnb API?',
    usedFor: ['Annonser', 'Bookinger', 'Ledighet'],
  },
  {
    service: 'visbook',
    name: 'Visbook',
    description: 'Channel manager og booking-plattform for reiseliv.',
    icon: '📱',
    color: '#007bff',
    category: 'Reiseliv & Overnatting',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din Visbook API key', type: 'password' },
      { key: 'property_id', label: 'Eiendom-ID', placeholder: '123456', type: 'text' },
    ],
    helpUrl: 'https://visbook.com/partner',
    helpLabel: 'Hvordan får jeg Visbook API-tilgang?',
    usedFor: ['Channel manager', 'Gjestehåndtering', 'Bookinger'],
  },
  {
    service: 'tripadvisor',
    name: 'TripAdvisor',
    description: 'Håndter anmeldelser og gjesterelasjon fra TripAdvisor.',
    icon: '⭐',
    color: '#00a82d',
    category: 'Reiseliv & Overnatting',
    fields: [
      { key: 'api_key', label: 'API Key', placeholder: 'Lim inn din TripAdvisor API key', type: 'password' },
      { key: 'property_id', label: 'Property ID', placeholder: '123456', type: 'text' },
    ],
    helpUrl: 'https://developer.tripadvisor.com/',
    helpLabel: 'Hvordan får jeg TripAdvisor API-tilgang?',
    usedFor: ['Anmeldelser', 'Gjestekommunikasjon', 'Rykteføring'],
  },
]

export const automationToIntegrations: Record<string, string[]> = {
  'fakturering':             ['vipps', 'tripletex', 'fiken', 'sendgrid'],
  'booking':                 ['google_calendar', 'outlook', 'sendgrid', 'twilio'],
  'salongbooking':           ['timely', 'fixit', 'sendgrid', 'twilio'],
  'kundeuppfølging':         ['tripletex', 'fiken', 'mailchimp', 'hubspot'],
  'leadgenerering':          ['hubspot', 'mailchimp', 'klaviyo'],
  'channel-manager':         ['booking_com', 'airbnb', 'visbook'],
  'sosialmedie-publisering': ['facebook', 'instagram', 'twitter', 'linkedin', 'youtube'],
  'podcast-publisering':     ['spotify', 'youtube'],
  'video-publisering':       ['youtube'],
  'klipp-generering':        ['youtube', 'facebook'],
  'lead-scraping':           ['finn_generell', 'google_maps'],
  'google-anmeldelser':      ['google_business'],
  'ruteplanlegging':         ['google_maps'],
  'prosjektstyring':         ['bygglet', 'fonn'],
  'kvalitetssikring':        ['fonn'],
  'tidsregistrering':        ['bygglet'],
  'eiendomsannonser':        ['vitec_next', 'finn_eiendom'],
  'e-signering':             ['signicat'],
  'visninger':               ['vitec_next', 'google_calendar'],
  'pos-betaling':            ['square'],
  'kundebehandling-salong':  ['timely', 'fixit'],
  'teknisk-oppslag':         ['autodata', 'infomedia'],
  'bilannonser':             ['finn_bil'],
  'serviceplanlegging':      ['autodata', 'google_calendar'],
  'gjestehåndtering':        ['visbook', 'booking_com'],
  'anmeldelser':             ['tripadvisor', 'google_business'],
  'overnattingsbooking':     ['booking_com', 'airbnb', 'visbook'],
}

export const categories = [
  'Felles',
  'Kommunikasjon & Prosjekt',
  'Sosiale Medier',
  'Betaling & Finans',
  'Markedsføring & E-post',
  'Data & Kart',
  'Bygg & Håndverk',
  'Eiendomsmegling',
  'Salong & Skjønnhet',
  'Bilverksted & Bilforhandler',
  'Reiseliv & Overnatting',
]

export const categoryIcons: Record<string, string> = {
  'Felles': '⚡',
  'Kommunikasjon & Prosjekt': '💬',
  'Sosiale Medier': '📱',
  'Betaling & Finans': '💰',
  'Markedsføring & E-post': '📧',
  'Data & Kart': '🗺️',
  'Bygg & Håndverk': '🏗️',
  'Eiendomsmegling': '🏠',
  'Salong & Skjønnhet': '💇',
  'Bilverksted & Bilforhandler': '🚗',
  'Reiseliv & Overnatting': '🏨',
}
